# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Himanshu Goyal
full_name: Himanshu Goyal
email: goyal.himanshu1799@gmail.com
email2: hg@iitbbs.ac.in
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://move47.github.io" # the base hostname & protocol for your site
# github_username:  move47
# twitter_username: Himansh1799
# linkedin_username: himanshu-goyal-7b466b148
# #stackoverflow: 5080995/martianwars
github_username:  move47
twitter_username: move_4_7
linkedin_username: himanshu-goyal-7b466b148
#stackoverflow: 5080995/martianwars
include: ['_pages']
footer-links-active:
  stackoverflow: false

# Build settings
markdown: kramdown
gems:
  # - jekyll-seo-tag
  - jekyll-redirect-from
